# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Shop
  	pod 'Firebase/Core'
  	pod 'Firebase/AdMob'
	pod 'Firebase/Messaging'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'Firebase/Firestore'
	pod 'Firebase/Functions'

  target 'Shop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
